# config/_default/languages.en.toml

title = "Brian Vu"

[author]
name = "Brian Vu"
image = "img/author.jpg"
headline = "Software Developer"
bio = "Connect with me"
links = [
  { linkedin = "https://www.linkedin.com/in/brian-vu-525898108/" },
  { github = "https://github.com/bvu12" },
  { email = "mailto:brian.vu12@gmail.com" }
]